// media-data.js

export const ELF_STUFF = [
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_002.avif",
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_018.avif",
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_035.avif",
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_066.avif",
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_114.avif",
  "https://www.stevencasteel.com/assets/portfolio/elf_girls/elf_girl_146.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_005.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_016.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_028.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_035.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_053.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_058.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_076.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_094.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_128.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_166.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_173.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/anime_screenshot/anime_screenshot_175.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_003.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_059.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_087.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_116.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_119.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_146.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_159.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_200.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_219.avif",
  "https://www.stevencasteel.com/assets/portfolio/esper_elfy/elfy_exploration/elfy_exploration_222.avif"
];

export const MISC_MEDIA = [
  "https://www.stevencasteel.com/assets/interests/books/captain_underpants.avif",
  "https://www.stevencasteel.com/assets/interests/books/charlie_and_the_chocolate_factory.avif",
  "https://www.stevencasteel.com/assets/interests/books/charlottes_web.avif",
  "https://www.stevencasteel.com/assets/interests/books/dragon_ball_vol_1.avif",
  "https://www.stevencasteel.com/assets/interests/books/dune.avif",
  "https://www.stevencasteel.com/assets/interests/books/his_dark_materials_trilogy.avif",
  "https://www.stevencasteel.com/assets/interests/books/mistborn_1_the_final_empire.avif",
  "https://www.stevencasteel.com/assets/interests/books/snow_crash.avif",
  "https://www.stevencasteel.com/assets/interests/books/steal_like_an_artist.avif",
  "https://www.stevencasteel.com/assets/interests/books/the_berenstain_bears_and_the_messy_room.avif",
  "https://www.stevencasteel.com/assets/interests/books/the_complete_calvin_and_hobbes.avif",
  "https://www.stevencasteel.com/assets/interests/books/the_giver.avif",
  "https://www.stevencasteel.com/assets/interests/books/the_hitchhikers_guide_to_the_galaxy.avif",
  "https://www.stevencasteel.com/assets/interests/books/the_hobbit.avif",
  "https://www.stevencasteel.com/assets/interests/movies/american_beauty.avif",
  "https://www.stevencasteel.com/assets/interests/movies/austin_powers_1.avif",
  "https://www.stevencasteel.com/assets/interests/movies/big_trouble_in_little_china.avif",
  "https://www.stevencasteel.com/assets/interests/movies/contact.avif",
  "https://www.stevencasteel.com/assets/interests/movies/dbz_the_history_of_trunks.avif",
  "https://www.stevencasteel.com/assets/interests/movies/dogma.avif",
  "https://www.stevencasteel.com/assets/interests/movies/falling_down.avif",
  "https://www.stevencasteel.com/assets/interests/movies/highlander.avif",
  "https://www.stevencasteel.com/assets/interests/movies/killer_klowns_from_outer_space.avif",
  "https://www.stevencasteel.com/assets/interests/movies/little_shop_of_horrors.avif",
  "https://www.stevencasteel.com/assets/interests/movies/robocop.avif",
  "https://www.stevencasteel.com/assets/interests/movies/star_wars_episode_vi_return_of_the_jedi.avif",
  "https://www.stevencasteel.com/assets/interests/movies/the_brave_little_toaster.avif",
  "https://www.stevencasteel.com/assets/interests/movies/the_fly.avif",
  "https://www.stevencasteel.com/assets/interests/movies/the_karate_kid_1984.avif",
  "https://www.stevencasteel.com/assets/interests/movies/the_princess_bride.avif",
  "https://www.stevencasteel.com/assets/interests/movies/they_live.avif",
  "https://www.stevencasteel.com/assets/interests/movies/uhf.avif",
  "https://www.stevencasteel.com/assets/interests/tv/adventure_time.avif",
  "https://www.stevencasteel.com/assets/interests/tv/atlanta.avif",
  "https://www.stevencasteel.com/assets/interests/tv/avatar_the_last_airbender.avif",
  "https://www.stevencasteel.com/assets/interests/tv/batman_1966.avif",
  "https://www.stevencasteel.com/assets/interests/tv/doctor_who_10.avif",
  "https://www.stevencasteel.com/assets/interests/tv/fargo.avif",
  "https://www.stevencasteel.com/assets/interests/tv/firefly.avif",
  "https://www.stevencasteel.com/assets/interests/tv/flight_of_the_conchords.avif",
  "https://www.stevencasteel.com/assets/interests/tv/freaks_and_geeks.avif",
  "https://www.stevencasteel.com/assets/interests/tv/futurama.avif",
  "https://www.stevencasteel.com/assets/interests/tv/invader_zim.avif",
  "https://www.stevencasteel.com/assets/interests/tv/jonny_quest.avif",
  "https://www.stevencasteel.com/assets/interests/tv/malcolm_in_the_middle.avif",
  "https://www.stevencasteel.com/assets/interests/tv/mob_psycho_100.avif",
  "https://www.stevencasteel.com/assets/interests/tv/pokemon.avif",
  "https://www.stevencasteel.com/assets/interests/tv/primal.avif",
  "https://www.stevencasteel.com/assets/interests/tv/reboot.avif",
  "https://www.stevencasteel.com/assets/interests/tv/smallville.avif",
  "https://www.stevencasteel.com/assets/interests/tv/speed_racer.avif",
  "https://www.stevencasteel.com/assets/interests/tv/star_trek.avif",
  "https://www.stevencasteel.com/assets/interests/tv/star_wars_clone_wars.avif",
  "https://www.stevencasteel.com/assets/interests/tv/stargate_sg_1.avif",
  "https://www.stevencasteel.com/assets/interests/tv/super_friends.avif",
  "https://www.stevencasteel.com/assets/interests/tv/terminator_the_sarah_connor_chronicles.avif",
  "https://www.stevencasteel.com/assets/interests/tv/the_twilight_zone.avif",
  "https://www.stevencasteel.com/assets/interests/tv/the_venture_bros.avif"
];

export const AUDIO_TRACKS = [
  { name: "001_01_Duath_Maethor.mp3", folder: "elf_girl_001", title: "001_01 Duath Maethor" },
  { name: "001_02_Falas_Idh.mp3", folder: "elf_girl_001", title: "001_02 Falas Idh" },
  { name: "001_04_Golodhram_Sereg.mp3", folder: "elf_girl_001", title: "001_04 Golodhram Sereg" },
  { name: "001_05_Pith_Niben.mp3", folder: "elf_girl_001", title: "001_05 Pith Niben" },
  { name: "001_12_Nath_Aglar.mp3", folder: "elf_girl_001", title: "001_12 Nath Aglar" },
  { name: "002_01_Miltaurath.mp3", folder: "elf_girl_002", title: "002_01 Miltaurath" },
  { name: "002_04_Harn_Galu.mp3", folder: "elf_girl_002", title: "002_04 Harn Galu" },
  { name: "002_10_Narn_Gwath.mp3", folder: "elf_girl_002", title: "002_10 Narn Gwath" },
  { name: "003_01_Edlothiad.mp3", folder: "elf_girl_003", title: "003_01 Edlothiad" },
  { name: "003_02_Lach_Gur.mp3", folder: "elf_girl_003", title: "003_02 Lach Gur" },
  { name: "003_29_Linnod_Tal_Blendor.mp3", folder: "elf_girl_003", title: "003_29 Linnod Tal Blendor" },
  { name: "004_01_Tyalieli_Vende.mp3", folder: "elf_girl_004", title: "004_01 Tyalieli Vende" },
  { name: "004_02_Tolo_na_Naur.mp3", folder: "elf_girl_004", title: "004_02 Tolo na Naur" },
  { name: "004_05_Edraith_o_Rhach.mp3", folder: "elf_girl_004", title: "004_05 Edraith o Rhach" },
  { name: "004_07_Lairelosse_Nith.mp3", folder: "elf_girl_004", title: "004_07 Lairelosse Nith" },
  { name: "004_08_Sanga_Ulundo.mp3", folder: "elf_girl_004", title: "004_08 Sanga Ulundo" },
  { name: "004_09_Sereg_Glir.mp3", folder: "elf_girl_004", title: "004_09 Sereg Glir" },
  { name: "004_11_Thol_Glae.mp3", folder: "elf_girl_004", title: "004_11 Thol Glae" },
  { name: "004_12_Vasa_Oiolaire.mp3", folder: "elf_girl_004", title: "004_12 Vasa Oiolaire" },
  { name: "004_13_Tul_Pent.mp3", folder: "elf_girl_004", title: "004_13 Tul Pent" },
  { name: "004_18_Gonod_Menel.mp3", folder: "elf_girl_004", title: "004_18 Gonod Menel" },
  { name: "004_20_Palantir_Mornie.mp3", folder: "elf_girl_004", title: "004_20 Palantir Mornie" },
  { name: "005_01_A_Apsene_Te.mp3", folder: "elf_girl_005", title: "005_01 A Apsene Te" },
  { name: "005_02_Liquis_Ear.mp3", folder: "elf_girl_005", title: "005_02 Liquis Ear" },
  { name: "005_03_Morn_Amloth.mp3", folder: "elf_girl_005", title: "005_03 Morn Amloth" },
  { name: "005_05_Hrave_Olori.mp3", folder: "elf_girl_005", title: "005_05 Hrave Olori" },
  { name: "005_14_Dram_Lim.mp3", folder: "elf_girl_005", title: "005_14 Dram Lim" },
  { name: "005_15_Tulca_Fea.mp3", folder: "elf_girl_005", title: "005_15 Tulca Fea" },
  { name: "005_18_A_Mape_Maryat.mp3", folder: "elf_girl_005", title: "005_18 A Mape Maryat" },
  { name: "006_01_Glaur_Fuin.mp3", folder: "elf_girl_006", title: "006_01 Glaur Fuin" },
  { name: "006_03_Glawar_Uruloke.mp3", folder: "elf_girl_006", title: "006_03 Glawar Uruloke" },
  { name: "006_06_Nessima_Tinwe.mp3", folder: "elf_girl_006", title: "006_06 Nessima Tinwe" },
  { name: "006_08_Voronda_Estel.mp3", folder: "elf_girl_006", title: "006_08 Voronda Estel" },
  { name: "006_11_Estel_Mornie.mp3", folder: "elf_girl_006", title: "006_11 Estel Mornie" },
  { name: "006_12_Ondo_Cale.mp3", folder: "elf_girl_006", title: "006_12 Ondo Cale" },
  { name: "006_13_Lisse_Lenda.mp3", folder: "elf_girl_006", title: "006_13 Lisse Lenda" },
  { name: "006_18_Elen_Sila.mp3", folder: "elf_girl_006", title: "006_18 Elen Sila" },
  { name: "006_21_Laire_Mordo.mp3", folder: "elf_girl_006", title: "006_21 Laire Mordo" },
  { name: "007_01_Angwedh_Thinnas.mp3", folder: "elf_girl_007", title: "007_01 Angwedh Thinnas" },
  { name: "007_03_Bregedur.mp3", folder: "elf_girl_007", title: "007_03 Bregedur" },
  { name: "007_06_Raucima_Linde.mp3", folder: "elf_girl_007", title: "007_06 Raucima Linde" },
  { name: "007_07_Tuima_More.mp3", folder: "elf_girl_007", title: "007_07 Tuima More" },
  { name: "007_08_Lamatyave_Hlapula.mp3", folder: "elf_girl_007", title: "007_08 Lamatyave Hlapula" },
  { name: "007_10_Quiesse_Calina.mp3", folder: "elf_girl_007", title: "007_10 Quiesse Calina" },
  { name: "007_14_Ea_Lomelinde.mp3", folder: "elf_girl_007", title: "007_14 Ea Lomelinde" },
  { name: "007_15_Taur_Gond.mp3", folder: "elf_girl_007", title: "007_15 Taur Gond" },
  { name: "007_17_Sure_Mirima.mp3", folder: "elf_girl_007", title: "007_17 Sure Mirima" },
  { name: "008_01_Galu_na_Vea.mp3", folder: "elf_girl_008", title: "008_01 Galu na Vea" },
  { name: "008_02_Mael_Amarth.mp3", folder: "elf_girl_008", title: "008_02 Mael Amarth" },
  { name: "008_03_Celu_Meluina.mp3", folder: "elf_girl_008", title: "008_03 Celu Meluina" },
  { name: "008_08_Alcar_mi_More.mp3", folder: "elf_girl_008", title: "008_08 Alcar mi More" },
  { name: "008_09_Miw_Wende.mp3", folder: "elf_girl_008", title: "008_09 Miw Wende" },
  { name: "008_15_Glawar_Idh.mp3", folder: "elf_girl_008", title: "008_15 Glawar Idh" },
  { name: "008_18_Anirog_Aes.mp3", folder: "elf_girl_008", title: "008_18 Anirog Aes" },
  { name: "008_22_Na_Ya_Na.mp3", folder: "elf_girl_008", title: "008_22 Na Ya Na" }
];