const PORTFOLIO_BASE = 'https://www.stevencasteel.com/assets/portfolio/';
const INTERESTS_BASE = 'https://www.stevencasteel.com/assets/interests/';

const ART_GROUPS = {
  clickbait_thumbnails: [
    'clickbait_22',
    'clickbait_35',
    'clickbait_37',
    'clickbait_38',
    'clickbait_49',
  ],
  elf_chartreuse: ['ec_001', 'ec_002', 'ec_007', 'ec_076', 'ec_089'],
  elf_girls: [
    'elf_girl_002',
    'elf_girl_018',
    'elf_girl_035',
    'elf_girl_043',
    'elf_girl_044',
    'elf_girl_045',
    'elf_girl_047',
    'elf_girl_048',
    'elf_girl_057',
    'elf_girl_066',
    'elf_girl_114',
    'elf_girl_116',
    'elf_girl_146',
    'elf_girl_184',
    'elf_girl_207',
    'elf_girl_272',
    'elf_girl_278',
    'elf_girl_296',
  ],
  elf_nocturne: ['elf_noc_01', 'elf_noc_03', 'elf_noc_08'],
  elf_technomancers: ['et_007', 'et_023', 'et_037'],
  'esper_elfy/anime_screenshot': [
    'anime_screenshot_005',
    'anime_screenshot_016',
    'anime_screenshot_028',
    'anime_screenshot_035',
    'anime_screenshot_053',
    'anime_screenshot_058',
    'anime_screenshot_076',
    'anime_screenshot_094',
    'anime_screenshot_128',
    'anime_screenshot_166',
    'anime_screenshot_173',
    'anime_screenshot_175',
  ],
  'esper_elfy/elfy_alien_planet': [
    'elfy_alien_planet_01',
    'elfy_alien_planet_05',
    'elfy_alien_planet_25',
    'elfy_alien_planet_31',
    'elfy_alien_planet_43',
  ],
  'esper_elfy/elfy_exploration': [
    'elfy_exploration_003',
    'elfy_exploration_059',
    'elfy_exploration_087',
    'elfy_exploration_116',
    'elfy_exploration_119',
    'elfy_exploration_146',
    'elfy_exploration_159',
    'elfy_exploration_200',
    'elfy_exploration_219',
    'elfy_exploration_222',
  ],
  'esper_elfy/elfy_sora2': ['elfy_sora2_25', 'elfy_sora2_26', 'elfy_sora2_35'],
  'esper_elfy/esper_elfy_character': [
    'esper_elfy_character_001F_sm',
    'esper_elfy_character_002_sm',
    'esper_elfy_character_042A_sm',
    'esper_elfy_character_057A_sm',
    'esper_elfy_character_065_sm',
    'esper_elfy_character_068_sm',
    'esper_elfy_character_070_sm',
    'esper_elfy_character_074B_sm',
    'esper_elfy_character_078_sm',
    'esper_elfy_character_081_sm',
    'esper_elfy_character_099A_sm',
    'esper_elfy_character_140A_sm',
    'esper_elfy_character_141_sm',
    'esper_elfy_character_142A_sm',
    'esper_elfy_character_144_sm',
    'esper_elfy_character_155_sm',
    'esper_elfy_character_156_sm',
    'esper_elfy_character_158_sm',
    'esper_elfy_character_173_sm',
    'esper_elfy_character_183_sm',
    'esper_elfy_character_187_sm',
    'esper_elfy_character_192A_sm',
    'esper_elfy_character_200B_sm',
    'esper_elfy_character_201_sm',
    'esper_elfy_character_206B_sm',
    'esper_elfy_character_209_sm',
    'esper_elfy_character_216_sm',
    'esper_elfy_character_219_sm',
    'esper_elfy_character_221A_sm',
    'esper_elfy_character_222_sm',
    'esper_elfy_character_225_sm',
    'esper_elfy_character_232_sm',
    'esper_elfy_character_239_sm',
    'esper_elfy_character_244_sm',
    'esper_elfy_character_245_sm',
    'esper_elfy_character_247_sm',
    'esper_elfy_character_248_sm',
  ],
  frutiger_liminal: [
    'fru_lim_001',
    'fru_lim_005',
    'fru_lim_024',
    'fru_lim_026',
    'fru_lim_038',
    'fru_lim_039',
    'fru_lim_043',
    'fru_lim_057',
    'fru_lim_065',
    'fru_lim_109',
    'fru_lim_120',
    'fru_lim_122',
    'fru_lim_123',
    'fru_lim_129',
    'fru_lim_131',
    'fru_lim_132',
    'fru_lim_134',
    'fru_lim_178',
    'fru_lim_194',
    'fru_lim_195',
    'fru_lim_202',
    'fru_lim_217',
    'fru_lim_235',
    'fru_lim_238',
    'fru_lim_250',
    'fru_lim_254',
  ],
  'gpt%20_image2_covers': [
    'gpt2_001',
    'gpt2_002',
    'gpt2_003',
    'gpt2_004',
    'gpt2_005',
    'gpt2_006',
    'gpt2_007',
    'gpt2_008',
    'gpt2_009',
    'gpt2_016',
    'gpt2_018',
    'gpt2_023',
    'gpt2_026',
    'gpt2_031',
    'gpt2_039',
    'gpt2_062',
    'gpt2_069',
    'gpt2_071',
    'gpt2_072',
    'gpt2_076',
    'gpt2_079',
  ],
  imagen3_business: ['imgn_bus_004', 'imgn_bus_021', 'imgn_bus_048'],
  imagen3_product: [
    'imgn_pro_012',
    'imgn_pro_086',
    'imgn_pro_162',
    'imgn_pro_229',
    'imgn_pro_466',
    'imgn_pro_493',
  ],
  kaiju_cats: ['kaiju_cat_01', 'kaiju_cat_15'],
  monster_drugs: ['monster_drugs_02', 'monster_drugs_04'],
  mushishi: [
    'mushishi_06',
    'mushishi_07',
    'mushishi_10',
    'mushishi_15',
    'mushishi_35',
    'mushishi_38',
    'mushishi_45',
    'mushishi_47',
  ],
  seedream3_covers: [
    'sc_001',
    'sc_002',
    'sc_004',
    'sc_005',
    'sc_008',
    'sc_009',
    'sc_012',
    'sc_013',
    'sc_021',
    'sc_030',
    'sc_042',
    'sc_043',
    'sc_046',
    'sc_049',
    'sc_052',
    'sc_054',
    'sc_057',
    'sc_063',
    'sc_085',
  ],
};

const MEDIA_GROUPS = {
  books: [
    'captain_underpants',
    'charlie_and_the_chocolate_factory',
    'charlottes_web',
    'dragon_ball_vol_1',
    'dune',
    'his_dark_materials_trilogy',
    'mistborn_1_the_final_empire',
    'snow_crash',
    'steal_like_an_artist',
    'the_berenstain_bears_and_the_messy_room',
    'the_complete_calvin_and_hobbes',
    'the_giver',
    'the_hitchhikers_guide_to_the_galaxy',
    'the_hobbit',
  ],
  movies: [
    'air_bud',
    'alien',
    'american_beauty',
    'august_rush',
    'austin_powers_1',
    'batman_beyond_return_of_the_joker',
    'big_trouble_in_little_china',
    'contact',
    'coraline',
    'dbz_the_history_of_trunks',
    'dogma',
    'dragon_ball_super_broly',
    'dredd',
    'falling_down',
    'fear_and_loathing_in_las_vegas',
    'fight_club',
    'friday',
    'from_dusk_till_dawn',
    'galaxy_quest',
    'ghostbusters_1',
    'highlander',
    'how_the_grinch_stole_christmas_2000',
    'indiana_jones_2',
    'killer_klowns_from_outer_space',
    'limitless',
    'little_shop_of_horrors',
    'megamind',
    'men_in_black_1',
    'muppet_treasure_island',
    'nimona',
    'office_space',
    'pirates_of_silicon_valley',
    'predator_badlands',
    'robocop',
    'rush_hour',
    'scott_pilgrim_vs_the_world',
    'send_help',
    'shrek',
    'signs',
    'smart_house',
    'south_park_bigger_longer_and_uncut',
    'space_jam',
    'spider_man_2',
    'spider_man_no_way_home',
    'star_wars_episode_i_the_phantom_menace',
    'star_wars_episode_vi_return_of_the_jedi',
    'starship_troopers',
    'tenacious_d_in_the_pick_of_destiny',
    'terminator_2',
    'the_amazing_spider_man',
    'the_batman',
    'the_brave_little_toaster',
    'the_fly',
    'the_hudsucker_proxy',
    'the_karate_kid_1984',
    'the_land_before_time',
    'the_matrix',
    'the_princess_bride',
    'the_rescuers',
    'the_rocketeer',
    'the_sixth_sense',
    'the_super_mario_bros_movie',
    'the_time_travelers_wife',
    'the_truman_show',
    'they_live',
    'tombstone',
    'toy_story_2',
    'tremors',
    'twilight_1',
    'uhf',
    'upgrade',
    'walk_hard_the_dewey_cox_story',
    'what_we_do_in_the_shadows_movie',
  ],
  tv: [
    'adventure_time',
    'atlanta',
    'avatar_the_last_airbender',
    'batman_1966',
    'doctor_who_10',
    'fargo',
    'firefly',
    'flight_of_the_conchords',
    'freaks_and_geeks',
    'futurama',
    'invader_zim',
    'jonny_quest',
    'malcolm_in_the_middle',
    'mob_psycho_100',
    'pokemon',
    'primal',
    'reboot',
    'smallville',
    'speed_racer',
    'star_trek',
    'star_wars_clone_wars',
    'stargate_sg_1',
    'super_friends',
    'terminator_the_sarah_connor_chronicles',
    'the_twilight_zone',
    'the_venture_bros',
  ],
};

const AUDIO_TRACK_GROUPS = {
  elf_girl_001: [
    '001_01_Duath_Maethor.mp3',
    '001_02_Falas_Idh.mp3',
    '001_04_Golodhram_Sereg.mp3',
    '001_05_Pith_Niben.mp3',
    '001_12_Nath_Aglar.mp3',
  ],
  elf_girl_002: ['002_01_Miltaurath.mp3', '002_04_Harn_Galu.mp3', '002_10_Narn_Gwath.mp3'],
  elf_girl_003: ['003_01_Edlothiad.mp3', '003_02_Lach_Gur.mp3', '003_29_Linnod_Tal_Blendor.mp3'],
  elf_girl_004: [
    '004_01_Tyalieli_Vende.mp3',
    '004_02_Tolo_na_Naur.mp3',
    '004_05_Edraith_o_Rhach.mp3',
    '004_07_Lairelosse_Nith.mp3',
    '004_08_Sanga_Ulundo.mp3',
    '004_09_Sereg_Glir.mp3',
    '004_11_Thol_Glae.mp3',
    '004_12_Vasa_Oiolaire.mp3',
    '004_13_Tul_Pent.mp3',
    '004_18_Gonod_Menel.mp3',
    '004_20_Palantir_Mornie.mp3',
  ],
  elf_girl_005: [
    '005_01_A_Apsene_Te.mp3',
    '005_02_Liquis_Ear.mp3',
    '005_03_Morn_Amloth.mp3',
    '005_05_Hrave_Olori.mp3',
    '005_14_Dram_Lim.mp3',
    '005_15_Tulca_Fea.mp3',
    '005_18_A_Mape_Maryat.mp3',
  ],
  elf_girl_006: [
    '006_01_Glaur_Fuin.mp3',
    '006_03_Glawar_Uruloke.mp3',
    '006_06_Nessima_Tinwe.mp3',
    '006_08_Voronda_Estel.mp3',
    '006_11_Estel_Mornie.mp3',
    '006_12_Ondo_Cale.mp3',
    '006_13_Lisse_Lenda.mp3',
    '006_18_Elen_Sila.mp3',
    '006_21_Laire_Mordo.mp3',
  ],
  elf_girl_007: [
    '007_01_Angwedh_Thinnas.mp3',
    '007_03_Bregedur.mp3',
    '007_06_Raucima_Linde.mp3',
    '007_07_Tuima_More.mp3',
    '007_08_Lamatyave_Hlapula.mp3',
    '007_10_Quiesse_Calina.mp3',
    '007_14_Ea_Lomelinde.mp3',
    '007_15_Taur_Gond.mp3',
    '007_17_Sure_Mirima.mp3',
  ],
  elf_girl_008: [
    '008_01_Galu_na_Vea.mp3',
    '008_02_Mael_Amarth.mp3',
    '008_03_Celu_Meluina.mp3',
    '008_08_Alcar_mi_More.mp3',
    '008_09_Miw_Wende.mp3',
    '008_15_Glawar_Idh.mp3',
    '008_18_Anirog_Aes.mp3',
    '008_22_Na_Ya_Na.mp3',
  ],
};

export const MISC_ART = Object.entries(ART_GROUPS).flatMap(([folder, files]) =>
  files.map((file) => `${PORTFOLIO_BASE}${folder}/${file}.avif`)
);

export const MISC_MEDIA = Object.entries(MEDIA_GROUPS).flatMap(([category, files]) =>
  files.map((file) => `${INTERESTS_BASE}${category}/${file}.avif`)
);

export const AUDIO_TRACKS = Object.entries(AUDIO_TRACK_GROUPS).flatMap(([folder, tracks]) =>
  tracks.map((name) => {
    const baseName = name.replace(/\.mp3$/, '');
    const parts = baseName.split('_');
    const title = parts.slice(0, 2).join('_') + ' ' + parts.slice(2).join(' ');

    return {
      name,
      folder,
      title,
    };
  })
);
